apiVersion: v1
kind: Secret
metadata:
  name: pages
data:
  index.html: PGgxPkhpITwvaDE+PHA+VGhpcyBpcyBhIHdlYiBwYWdlLjwvcD4=
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: pages
      mountPath: /usr/share/nginx/html
      readOnly: true
  volumes:
  - name: pages
    secret:
      secretName: pages
